name: news

on:
  workflow_dispatch:

jobs:
  news:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2

      - name: Get News
        run: Rscript get_news.R
          env:
            NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update news
          branch: main
